package taskstate

import "strings"

const (
	TaskEventAgentAction                           = "agent.action"
	TaskEventAgentAmbientDutyLaunch                = "agent.ambient_duty_launch"
	TaskEventAgentApprovalUserFacingMessageMissing = "agent.approval_user_facing_message_missing"
	TaskEventAgentArtifactAttachRejected           = "agent.artifact_attach_rejected"
	TaskEventAgentBudgetExtendedOneLevel           = "agent.budget_extended_one_level"
	TaskEventAgentBudgetUpdateSent                 = "agent.budget_update_sent"
	TaskEventAgentCheckpointFailed                 = "agent.checkpoint.failed"
	TaskEventAgentCheckpointSent                   = "agent.checkpoint.sent"
	TaskEventAgentCheckpointSkipped                = "agent.checkpoint.skipped"
	TaskEventAgentCompletionPersistFailed          = "agent.completion_persist_failed"
	TaskEventAgentCompletionReplyFailed            = "agent.completion_reply_failed"
	TaskEventAgentCompletionRequired               = "agent.completion_required"
	TaskEventAgentCompletionStateBestEffort        = "agent.completion_state_best_effort"
	TaskEventAgentCompletionStateFinalized         = "agent.completion_state_finalized"
	TaskEventAgentCompletionStateRejected          = "agent.completion_state_rejected"
	TaskEventAgentCompletionStateTransition        = "agent.completion_state_transition"
	TaskEventAgentConfirmationPlanDegraded         = "agent.confirmation_plan_degraded"
	TaskEventAgentConsumed                         = "agent.consumed"
	TaskEventAgentContextCompactionFreedNothing    = "agent.context_compaction_freed_nothing"
	TaskEventAgentContextSummary                   = "agent.context_summary"
	TaskEventAgentContractArbitrationDegraded      = "agent.contract_arbitration_degraded"
	TaskEventAgentConversationBudget               = "agent.conversation_budget"
	TaskEventAgentConversationScope                = "agent.conversation_scope"
	TaskEventAgentDuplicateToolCallRejected        = "agent.duplicate_tool_call_rejected"
	TaskEventAgentEvidenceMissing                  = "agent.evidence_missing"
	TaskEventAgentExecutionState                   = "agent.execution_state"
	TaskEventAgentExternalSendIntentRejected       = "agent.external_send_intent_rejected"
	TaskEventAgentExternalSendRepeatRejected       = "agent.external_send_repeat_rejected"
	TaskEventAgentFailedFingerprintRejected        = "agent.failed_fingerprint_rejected"
	TaskEventAgentFailureDebtCreated               = "agent.failure_debt_created"
	TaskEventAgentFailureReply                     = "agent.failure_reply"
	TaskEventAgentFailureReport                    = "agent.failure_report"
	TaskEventAgentFailureReportFactsUsed           = "agent.failure_report_facts_used"
	TaskEventAgentFailureReportRejected            = "agent.failure_report_rejected"
	TaskEventAgentFileReadCacheHit                 = "agent.file_read_cache_hit"
	TaskEventAgentFinalizerAction                  = "agent.finalizer_action"
	TaskEventAgentFinalizerEvidenceSupplied        = "agent.finalizer_evidence_supplied"
	TaskEventAgentFinalizerFailed                  = "agent.finalizer_failed"
	TaskEventAgentFinalizerRejected                = "agent.finalizer_rejected"
	TaskEventAgentGoalBlocked                      = "agent.goal.blocked"
	TaskEventAgentGoalCompleted                    = "agent.goal.completed"
	TaskEventAgentGoalCreated                      = "agent.goal.created"
	TaskEventAgentGoalUpdated                      = "agent.goal.updated"
	TaskEventAgentGoalWaitingApproval              = "agent.goal.waiting_approval"
	TaskEventAgentGoalWaitingUserInput             = "agent.goal.waiting_user_input"
	TaskEventAgentIdenticalOutput                  = "agent.identical_output"
	TaskEventAgentInstructionsLoaded               = "agent.instructions_loaded"
	TaskEventAgentIntake                           = "agent.intake"
	TaskEventAgentLaunchStepError                  = "agent.launch_step.error"
	TaskEventAgentLaunchStepResult                 = "agent.launch_step.result"
	TaskEventAgentLimitCompletedFromEvidence       = "agent.limit_completed_from_evidence"
	TaskEventAgentLimitPressure                    = "agent.limit_pressure"
	TaskEventAgentLimitReply                       = "agent.limit_reply"
	TaskEventAgentLimitStop                        = "agent.limit_stop"
	TaskEventAgentLLMUnavailable                   = "agent.llm_unavailable"
	TaskEventAgentNoProgressLoopPaused             = "agent.no_progress_loop_paused"
	TaskEventAgentNoProgressLoopStopped            = "agent.no_progress_loop_stopped"
	TaskEventAgentNonRetryableToolRefused          = "agent.non_retryable_tool_refused"
	TaskEventAgentPlanNudged                       = "agent.plan.nudged"
	TaskEventAgentPlanSized                        = "agent.plan.sized"
	TaskEventAgentPlanUpdated                      = "agent.plan.updated"
	TaskEventAgentQualityCriteria                  = "agent.quality_criteria"
	TaskEventAgentQualityReview                    = "agent.quality_review"
	TaskEventAgentRecoverableFailRejected          = "agent.recoverable_fail_rejected"
	TaskEventAgentRecoveryAttempt                  = "agent.recovery_attempt"
	TaskEventAgentRecoveryBudgetExhausted          = "agent.recovery_budget_exhausted"
	TaskEventAgentRecoveryGenerationFailed         = "agent.recovery_generation_failed"
	TaskEventAgentRecoveryGuidance                 = "agent.recovery_guidance"
	TaskEventAgentRepeatedToolCall                 = "agent.repeated_tool_call"
	TaskEventAgentStallBlockedReply                = "agent.stall_blocked_reply"
	TaskEventAgentStallExitDirective               = "agent.stall_exit_directive"
	TaskEventAgentStallPauseReply                  = "agent.stall_pause_reply"
	TaskEventAgentStallRecoveryDirective           = "agent.stall_recovery_directive"
	TaskEventAgentStepWorkingSet                   = "agent.step_working_set"
	TaskEventAgentSuggestedNextToolDirective       = "agent.suggested_next_tool_directive"
	TaskEventAgentTaskLaunched                     = "agent.task_launched"
	TaskEventAgentTaskSource                       = "agent.task_source"
	TaskEventAgentTerminalNoToolsAction            = "agent.terminal_no_tools_action"
	TaskEventAgentTerminalNoToolsRejected          = "agent.terminal_no_tools_rejected"
	TaskEventAgentToolInputMalformed               = "agent.tool_input_malformed"
	TaskEventAgentToolResultImagesRestored         = "agent.tool_result_images_restored"
	TaskEventAgentToolResultsPruned                = "agent.tool_results_pruned"
	TaskEventAgentTurnAnchorClamped                = "agent.turn_anchor_clamped"
	TaskEventAgentUnchangedResult                  = "agent.unchanged_result"
	TaskEventAgentUnreadableAction                 = "agent.unreadable_action"
	TaskEventAgentValidityReview                   = "agent.validity_review"
	TaskEventApprovalContinued                     = "approval.continued"
	TaskEventApprovalDecided                       = "approval.decided"
	TaskEventApprovalExecuted                      = "approval.executed"
	TaskEventApprovalHeldCall                      = "approval.held_call"
	TaskEventApprovalPendingCall                   = "approval.pending_call"
	TaskEventApprovalScopeGranted                  = "approval.scope_granted"
	TaskEventApprovalUnheldCallCarriedOut          = "approval.unheld_call_carried_out"
	TaskEventAskReplyClassified                    = "ask.reply_classified"
	TaskEventAskRequested                          = "ask.requested"
	TaskEventAskResolved                           = "ask.resolved"
	TaskEventAskSupersededByMessage                = "ask.superseded_by_message"
	TaskEventBlueclawTaskExecutionDuration         = "blueclaw.task.execution_duration"
	TaskEventCompletionJudgeDegraded               = "completion_judge.degraded"
	TaskEventCompletionJudgeExpanded               = "completion_judge.expanded"
	TaskEventCompletionJudgeStandingVerdict        = "completion_judge.standing_verdict"
	TaskEventCompletionJudgeVerdict                = "completion_judge.verdict"
	TaskEventConfirmationClarificationRequested    = "confirmation.clarification_requested"
	TaskEventConfirmationPlanCreated               = "confirmation.plan_created"
	TaskEventConfirmationPolicyDecision            = "confirmation.policy_decision"
	TaskEventConfirmationRejected                  = "confirmation.rejected"
	TaskEventConfirmationReplaced                  = "confirmation.replaced"
	TaskEventConfirmationReplyClassified           = "confirmation.reply_classified"
	TaskEventConfirmationRequested                 = "confirmation.requested"
	TaskEventConnectorDuplicateSourceSuppressed    = "connector.duplicate_source_suppressed"
	TaskEventConnectorReactionFailed               = "connector.reaction.failed"
	TaskEventConnectorReactionSent                 = "connector.reaction.sent"
	TaskEventConnectorReactionSkipped              = "connector.reaction.skipped"
	TaskEventConnectorReplyEnqueued                = "connector.reply.enqueued"
	TaskEventConnectorReplyFailed                  = "connector.reply.failed"
	TaskEventConnectorReplySent                    = "connector.reply.sent"
	TaskEventConnectorReplySuppressed              = "connector.reply.suppressed"
	TaskEventDelegateFinished                      = "delegate.finished"
	TaskEventDelegateLaunched                      = "delegate.launched"
	TaskEventHarnessToolPermitted                  = "harness.tool_permitted"
	TaskEventHarnessToolRefused                    = "harness.tool_refused"
	TaskEventLLMCall                               = "llm.call"
	TaskEventMemoryPinnedLoadFailed                = "memory.pinned_load_failed"
	TaskEventMemoryPinnedLoadSucceeded             = "memory.pinned_load_succeeded"
	TaskEventReplySuppressedDuplicate              = "reply.suppressed_duplicate"
	TaskEventScheduleCancelled                     = "schedule.cancelled"
	TaskEventScheduleCreated                       = "schedule.created"
	TaskEventScheduleUpdated                       = "schedule.updated"
	TaskEventTaskAbandonedByTurn                   = "task.abandoned_by_turn"
	TaskEventTaskAutoResumeAbandoned               = "task.auto_resume_abandoned"
	TaskEventTaskAutoResumeAttempted               = "task.auto_resume_attempted"
	TaskEventTaskAutoResumeLaunchFailed            = "task.auto_resume_launch_failed"
	TaskEventTaskAutoResumeReplyUnavailable        = "task.auto_resume_reply_unavailable"
	TaskEventTaskAutoResumeSkipped                 = "task.auto_resume_skipped"
	TaskEventTaskBlocked                           = "task.blocked"
	TaskEventTaskBusyMessageAfterFinish            = "task.busy_message.after_finish"
	TaskEventTaskBusyMessageRouted                 = "task.busy_message.routed"
	TaskEventTaskCancelRequested                   = "task.cancel.requested"
	TaskEventTaskCancelled                         = "task.cancelled"
	TaskEventTaskCompleted                         = "task.completed"
	TaskEventTaskCreated                           = "task.created"
	TaskEventTaskFailed                            = "task.failed"
	TaskEventTaskInterrupted                       = "task.interrupted"
	TaskEventTaskModelVisibleContext               = "task.model_visible_context"
	TaskEventTaskObserverCrashed                   = "task.observer_crashed"
	TaskEventTaskPaused                            = "task.paused"
	TaskEventTaskReplaced                          = "task.replaced"
	TaskEventTaskRunning                           = "task.running"
	TaskEventTaskStaleExpired                      = "task.stale_expired"
	TaskEventTaskStatusRequested                   = "task.status.requested"
	TaskEventTaskSteerApplied                      = "task.steer.applied"
	TaskEventTaskSteerRequested                    = "task.steer.requested"
	TaskEventTaskSteerResumeUnavailable            = "task.steer.resume_unavailable"
	TaskEventTaskStopCancelled                     = "task.stop.cancelled"
	TaskEventTaskStopClassified                    = "task.stop.classified"
	TaskEventTaskStopOutboxSuppressed              = "task.stop.outbox_suppressed"
	TaskEventTaskStopRequested                     = "task.stop.requested"
	TaskEventTaskSupersededByMessage               = "task.superseded_by_message"
	TaskEventTaskWaitPersistFailed                 = "task.wait.persist_failed"
	TaskEventTaskWaitCancelled                     = "task.wait_cancelled"
	TaskEventTaskScheduleDeliveryEnqueued          = "task_schedule.delivery.enqueued"
	TaskEventTaskScheduleDeliveryFailed            = "task_schedule.delivery.failed"
	TaskEventTerminalRunHeartbeat                  = "terminal.run.heartbeat"
	TaskEventToolCrashed                           = "tool.crashed"
	TaskEventToolResultSpillFailed                 = "tool.result_spill_failed"
	TaskEventToolResultSpilled                     = "tool.result_spilled"
)

const (
	AgentGoalTaskEventPrefix     = "agent.goal."
	ToolTaskEventPrefix          = "tool."
	ToolTaskEventRequestedSuffix = ".requested"
	ToolTaskEventResultSuffix    = ".result"
	ToolTaskEventCancelledSuffix = ".cancelled"
)

func ToolTaskEventName(toolName string, suffix string) string {
	return ToolTaskEventPrefix + strings.TrimSpace(toolName) + suffix
}

func ToolTaskEventToolName(eventName string, suffix string) (string, bool) {
	trimmedEventName := strings.TrimSpace(eventName)
	if !strings.HasPrefix(trimmedEventName, ToolTaskEventPrefix) || !strings.HasSuffix(trimmedEventName, suffix) {
		return "", false
	}
	toolName := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(trimmedEventName, ToolTaskEventPrefix), suffix))
	return toolName, toolName != ""
}
